### ISSUE TITLE
Upgrade Mattermost at https://mattermost.openhwgroup.org/

### ISSUE THREAD

**Issue by eclipsewebmaster** [openhwgroup/infra#1]
‘slow typing’ performance issue that many user have experienced and has since been corrected in Jan, Mar and April releases https://mattermost.atlassian.net/browse/MM-30407

Also note: OpenHW Mattermost is typically a custom MM build with GitHub authentication. MM has since incorporated a generic OpenID connector, so we'll need to stage the upgrade and test the migration.

Scheduling for May 13, PM

**Comment by eclipsewebmaster** [comment]
I've had to roll back the upgrade, as the generic OpenID connector wasn't working with our settings. I will sandbox the install and try on the sandbox.

**Comment by zarubaf** [comment]
@eclipsewebmaster is there an estimated timeframe for the upgrade? The mentioned Mattermost issue makes it almost impossible to work with it in a browser session.

**Comment by eclipsewebmaster** [comment]
Not at this time, as we have nothing to upgrade to. GitHub does not offer OpenID authentication, only OAuth2, which is incompatible with MatterMost. MM has been providing custom builds with OAuth2 (which is what wer're using now) and we're working with MatterMost and reconsidering what our options are.

**Comment by rickoco** [comment]
@eclipsewebmaster - what is the status here since you've recommended a different Mattermost license?  The community continues to be frustrated by the performance issues previously reported.

**Comment by eclipsewebmaster** [comment]
I am unsure of the "different license" you refer to, but our upgrade path for Mattermost is complicated as per my previous comment.

**Comment by eclipsewebmaster** [comment]
As per discussions, we'll sandbox a second Mattermost instance that uses Eclipse Foundation accounts as a true OpenID source. We need to make sure the existing GitHub accounts are properly associated to their Eclipse counterparts.

We'll also need to work with the OpenHW community in ensuring everyone has an Eclipse account by the time we do the migration.

Sandbox to come....

**Comment by eclipsewebmaster** [comment]
Vacation season put us behind on this effort, but we are resuming it. Sandbox server has been created, we wil sandbox the existing MM site (using GH), use OpenID to Eclipse and see how we need to convert the current user accounts to work on OpenID.

**Comment by eclipsewebmaster** [comment]
OpenHW Mattermost is sandboxed, we're proceeding with experimental OpenID to determine the mapping of existing users.

**Comment by eclipsewebmaster** [comment]
Just to update, we are making progress with OpenID. This migration is top-priority.

**Comment by agafgfafa** [comment]
We are struggling with migrating :"github" users to OpenID. Also encountering https://github.com/mattermost/mattermost-server/pull/17933

**Comment by eclipsewebmaster** [comment]
We've managed to get new Mattermost to work on the sandbox server, and were successful in mapping test GitHub accounts to Eclipse OpenID.

We will try to match everyone to Eclipse OpenID, then report how many match / no-match we find.

**Comment by eclipsewebmaster** [comment]
We are almost ready for migration. There are 120 Users that do not have an Eclipse Foundation LDAP account. 83 Users do.

We`ll need all active OpenHW Mattermost participants to create an Eclipse Foundation account, and link it to your GitHub ID:

https://accounts.eclipse.org


We are targetting a Sept 30 cut-over date.

**Comment by eclipsewebmaster** [comment]
Reminder: tomorrow morning (CET) we are migrating the OpenHW Mattermost to use the Eclipse Foundation OpenID, as GitHub OAuth2 is not supported by Mattermost. Please create an Eclipse Foundation account if you do not have one, and link it to your GitHub ID:

https://accounts.eclipse.org

**Comment by eclipsewebmaster** [comment]
Migration of Mattermost to a new server has been completed. Authenticating via GitHub plugin is no longer possible. Authentication with login and password is still possible, but  using OpenID is now a preferred method. All users, that had a valid Eclipse Foundation account  were converted to OpenID authentication method.  Please contact us if you currently authenticate via login+password and you wish to convert to OpenID ( recommended).

**Comment by eclipsewebmaster** [comment]
Login+password authentication method has been switched off. Login is now possible only with OpenID

**Comment by eclipsewebmaster** [comment]
If you have a problem to login into MatterMost following the recent migration, you can follow this procedure.

If you **did not** have an Eclipse Foundation account before the migration.

1. Create the Eclipse Foundation account here: https://accounts.eclipse.org/
   Make sure, that your **username** and **e-mail** match your MatterMost account.
2. Contact us at webmaster@eclipse.org, so we can switch your MatterMost account to OpenId authentication.
    After we have replied to you, follow with the other steps.   


1. Clear your browser cache/saved logins for https://mattermost.openhwgroup.org page.
2. Go to https://accounts.eclipse.org and login with your e-mail address.
3. Go to https://mattermost.openhwgroup.org/login and click Login with Eclipse  Account

If you **did** have an Eclipse Foundation account before the migration, but you still cannot login.
It is probably because you used to login with password or via github profile that was not associated with  Eclipse Foundation account.

1. Contact us at webmaster@eclipse.org, so we can switch your MatterMost account to OpenId authentication.
    After we have replied to you, follow with the other steps. 

1. Clear your browser cache/saved logins for https://mattermost.openhwgroup.org page.
2. Go to https://accounts.eclipse.org and login with your e-mail address.
3. Go to https://mattermost.openhwgroup.org/login and click Login with Eclipse  Account

If you create a **new** Eclipse Foundation profile with **username** and **e-mail** that **differs** from your existing MatterMost account, you will be able to login, but as a new user. **It will not be possible to associate your new account with the original one** and you will not have access to the original account data.

If you have any doubts do not hesitate to contact us!
