### ISSUE TITLE
Migrate openhwgroup.org and osdforums.org to Eclipse infrastructure.

### ISSUE THREAD

**Issue by chrisguindon** [openhwgroup/infra#11]
These 2 websites are currently hosted with Netlify to enable developers to review a preview of their changes each time they submit an MR. However, over the years, the cost of using Netlify has increased significantly.

In an effort to reduce our costs, @mbarbero and his team created a new preview framework that we can use that run on the Eclipse Infrastructure.

For more information about this see: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1978

We would like to migrate openhwgroup.org and osdforums.org to Eclipse infrastructure on November 30 @ 9 am EST. 

There might be 30 minutes of downtime but we will do our best to have 0 min downtime.

@DBees and @rickoco Do you have any issues or concerns about this?

Let me know if you have any concerns with that date and we will accommodate! We do want to finalize this migration before mid-December.

Please note that we are replacing Netlify with a similar service. PRs will continue to generate links that your team can review before approving changes that my team as implemented.

**Comment by rickoco** [comment]
no issues for me on this @chrisguindon

**Comment by chrisguindon** [comment]
Thanks, @rickoco for the quick reply! I will schedule the work!

**Comment by chrisguindon** [comment]
The migration is complete! Please let us know if you see any problems!
