### ISSUE TITLE
No email notifications from Mattermost

### ISSUE THREAD

**Issue by griffin175** [openhwgroup/infra#12]
Notifications should be configured to send immediately for mentions and DMs when offline or away for more than 5 minutes.
I'm using the browser, not the desktop app.

![image](https://user-images.githubusercontent.com/56269216/220762873-61995c58-beff-43e2-b480-34e89aa67bd7.png)
![image](https://user-images.githubusercontent.com/56269216/220762905-db976628-7832-4fe8-8c77-62ff33752702.png)

I checked spam and trash folders. No luck.
Using the mobile app now.

**Comment by chrisguindon** [comment]
//cc @eclipsewebmaster

**Comment by DBees** [comment]
@eclipsewebmaster Are you able to respond to this please? I think there are several people who noticed that email notifications don't seem to work. Just from googling I think there is a global on/off for email notifications, can you please check into it? Thanks

**Comment by eclipsewebmaster** [comment]
@DBees I can confirm that the global notifications are and have always been set to on. I am looking into the issue

**Comment by DBees** [comment]
@eclipsewebmaster it is important that we get that working as some people are assuming email notifications. Any suggestions appreciated.

**Comment by eclipsewebmaster** [comment]
This should now be working.

Long story short: increased security on the account used to send email necessitated adding some custom rules to allow it to accept email from Mattermost.

**Comment by DBees** [comment]
cool, thanks @eclipsewebmaster

**Comment by griffin175** [comment]
Can confirm, I am receiving email notifications when tagged now.
