### ISSUE TITLE
Base permission for Members is wrongly reset to No Permission

### ISSUE THREAD

**Issue by DBees** [openhwgroup/infra#13]
I have set the member privileges to "Read" so that every member of the OpenHW Github (listed at https://github.com/orgs/openhwgroup/people) has Read privilege as a minimum. 
This allows OpenHW Github members to be assigned to issues. 

However, overnight, the permission is getting reset to "No Permission"
Here is the setting which is being reset. 
https://github.com/organizations/openhwgroup/settings/member_privileges

Is this setting being automatically reset by Eclipse scripts or otherwise? This is impeding our work.

**Comment by chrisguindon** [comment]
How is this impacting your work? 

We are setting this permission to protect private repos and restrict which user can see them.

This setting was discussed via https://gitlab.eclipse.org/eclipsefdn/it/webdev/eclipsefdn-vc-tools/-/issues/240

//cc @mbarbero

**Comment by DBees** [comment]
Without "Read" access, a person can't be assigned to an issue if they aren't a committer. They don't appear on the drop-down list when assigning an issue. We need to be able to assign any member of the OpenHW github organization to issues.

**Comment by DBees** [comment]
Also, all OpenHW repos are public

**Comment by chrisguindon** [comment]
> Also, all OpenHW repos are public

Private repos are used for dealing/fixing security issues that aren't public yet.

@mbarbero,

Are you ok with us implementing an exception for OpenHWGroup?

**Comment by mbarbero** [comment]
For the "assign someone to an issue" issue, we have implemented the "external contributor" thing in PMI. Would that be enough?

**Comment by DBees** [comment]
@mbarbero are you referring to the PMI interface which allows to provide contributors with Triage access? That solves a different problem, giving contributor X triage power, and the ability to assign an issue to member Y (as long as Y appears on the github drop down).

Our problem is that nobody (committers or those with triage powers) can assign anything to Y, because Y no longer appears on the Github issue assignment dropdown menu You need to give Y (all the OpenHW members) read access so that Y appears on the dropdown menu, that was confirmed through experimentation.

**Comment by chrisguindon** [comment]
> @mbarbero are you referring to the PMI interface which allows to provide contributors with Triage access? That solves a different problem, giving contributor X triage power, and the ability to assign an issue to member Y (as long as Y appears on the github drop down).

No, it also solves the "assignee" issue that you are reporting. Any contributor can be assigned to an issue on which they are a contributor.

**Comment by DBees** [comment]
So you are recommending we take all 120 ish OpenHW Github members and add them to contributor list via PMI?

**Comment by DBees** [comment]
Also for that to work, I think we would have to enable the contributor rights to apply to all non-CORE-V OpenHW repos, as they would only apply to the subset of OpenHW repos that are in the Eclipse CORE-V project.

**Comment by mbarbero** [comment]
> @mbarbero,
> 
> Are you ok with us implementing an exception for OpenHWGroup?

absolutely

**Comment by DBees** [comment]
@mbarbero @chrisguindon can we do this please.

**Comment by autumnfound** [comment]
There is a PR up for this, and it should be up in the next 24h unless there are issues with deployment

**Comment by DBees** [comment]
Ok @autumnfound  Please hurry, the permission is still getting reset and we can't move forward with assigning issues and updating project boards. FYI @LeeHoff @joecircello

**Comment by autumnfound** [comment]
> Ok @autumnfound Please hurry, the permission is still getting reset and we can't move forward with assigning issues and updating project boards. FYI @LeeHoff @joecircello

This is now be fixed. We've added a small exception in the sync script so that openhwgroup will retain read permission as default, and I've confirmed that this has run through our normal process.
