### ISSUE TITLE
CNAME DNS record

### ISSUE THREAD

**Issue by DBees** [openhwgroup/infra#15]
Hello @chrisguindon as I rebuilt the readthedocs domain, there is as new CNAME record that needs to be added
PLease also refer to https://github.com/openhwgroup/infra/issues/6 for how this was previously handled.

Domain Details
To configure this domain add a CNAME record in your DNS pointing your custom domain to [b1ad3f12.domains.readthedocs.com](http://b1ad3f12.domains.readthedocs.com/).

cheers
Duncan

**Comment by DBees** [comment]
The custom domain name is 
Domain: docs.openhwgroup.org

**Comment by eclipsewebmaster** [comment]
@DBees there is currently an existing record:

 `docs.openhwgroup.org IN CNAME e4089c14.domains.readthedocs.com`

So you want that replaced by:

`docs.openhwgroup.org IN CNAME b1ad3f12.domains.readthedocs.com`

Is that correct?

**Comment by DBees** [comment]
Hi @eclipsewebmaster that is my understanding. However at this moment, the URLs seem to be working - have you already implemented the above?

**Comment by eclipsewebmaster** [comment]
@DBees no, we didn't take any action yet

**Comment by DBees** [comment]
@eclipsewebmaster please go ahead and make the change and please flag me when done @DBees, so that I can verify we haven't broken the URL access to our documents. 

From my understanding the read the docs service provider moved the service to the new CNAME. The old seems to still work, but I guess we should update to the new one.

**Comment by eclipsewebmaster** [comment]
@DBees I changed the record as requested

**Comment by DBees** [comment]
@eclipsewebmaster thank you, all seems well, so we can close this issue. Thx.
