### ISSUE TITLE
New ANAME Record

### ISSUE THREAD

**Issue by zarubaf** [openhwgroup/infra#3]
Dear Infra team,

can we please have a new ANAME record from `avon.openhwgroup.org` to `34.248.29.167`

Thanks a lot!

**Comment by eclipsewebmaster** [comment]
I'll need to get a +1 from @DBees

**Comment by rickoco** [comment]
jumping in here for @DBees to say this is approved.  @eclipsewebmaster general question for you.  Why do you need a +1 at all?  @zarubaf is part of the OpenHW staff and has full authority on this :-)

**Comment by zarubaf** [comment]
Any update on this?

**Comment by zarubaf** [comment]
Ping!

**Comment by eclipsewebmaster** [comment]
Done.

**Comment by zarubaf** [comment]
@eclipsewebmaster  Can we please change the entry to a `CNAME` from:

`avon.openhwgroup.org` to `ec2-34-248-29-167.eu-west-1.compute.amazonaws.com`

please. Thanks.

**Comment by rickoco** [comment]
@zarubaf - are you still waiting on this or have you gone down another path?  If you're still waiting, pls let @chrisguindon or @eclipsewebmaster know

**Comment by zarubaf** [comment]
Still waiting. So would be nice if you we can implement it @chrisguindon

**Comment by chrisguindon** [comment]
I deleted the A record for avon.openhwgroup.org and created a new CNAME record with avon.openhwgroup.org to ec2-34-248-29-167.eu-west-1.compute.amazonaws.com

**Comment by eclipsewebmaster** [comment]
> 

Wasn't aware. Apologies for the delays, we seem to lose / not receive GitHub notifications. We've since tweaked the settings to ensure this does not happen again.

**Comment by zarubaf** [comment]
Thanks, that works now. Sorry for the mistake with the A-Name in the first place.
