### ISSUE TITLE
CNAME Record

### ISSUE THREAD

**Issue by zarubaf** [openhwgroup/infra#5]
Can you please set-up a CNAME record:

`downloads.openhwgroup.org`  to `downloads.openhwgroup.org.s3-website-eu-west-1.amazonaws.com`

Thanks

CC/@rickoco

**Comment by rickoco** [comment]
@chrisguindon - approved for creation…

**Comment by chrisguindon** [comment]
Done!

**Comment by rickoco** [comment]
Thx for the blazing response @chrisguindon !!

**Comment by chrisguindon** [comment]
YW - There was some luck involved here! I just happen to be looking at my email inbox! Have a good week-end @rickoco and @zarubaf
