### ISSUE TITLE
CNAME record for docs.openhwgroup.org

### ISSUE THREAD

**Issue by rickoco** [openhwgroup/infra#6]
@chrisguindon - can you please setup the following (this is for OpenHW readthedocs documentation):

Domain: docs.openhwgroup.org

To configure this domain add a CNAME record in your DNS pointing your custom domain to e4089c14.domains.readthedocs.com.

**Comment by chrisguindon** [comment]
This is already in place @rickoco

![Screenshot 2022-02-03 100410](https://user-images.githubusercontent.com/893942/152369050-6f3b88d4-c9be-4468-8203-d130bac0d537.jpg)

**Comment by chrisguindon** [comment]
Feel free to re-open if you are experiencing issues with this but it looks like we are already set...

**Comment by rickoco** [comment]
ok thx @chrisguindon - sorry for the hassle :-(
