### ISSUE TITLE
Permissions for project boards

### ISSUE THREAD

**Issue by DBees** [openhwgroup/infra#7]
It is my understanding that the project COMMITTER TEAM and CONTRIBUTOR TEAM have no bearing on permission settings for organization wide project board board. 

Web support team, please confirm the above. 

To implement the project boards,
- I'll be expanding the CONTRIBUTOR TEAM  roster for the purpose of giving Triage access on CORE-V CORES projects to those who need to see issue labels
- Initially, I'll be assigning write permission to the CVA6 project board https://github.com/orgs/openhwgroup/projects/3 to selected CVA6 contributors and committers who will need to move the status of their tasks through the project board

Webmaster/web support team please confirm this doesn't break anything regarding CORE-V Cores teams and permissions.

**Comment by DBees** [comment]
Any comment on above?

**Comment by chrisguindon** [comment]
From what I can tell, the board does not affect permission on the repo.

With this said, my recommendation would be for you to verify who has access to the repo after setting this up. You will be able to confirm that these contributors don't have write access:

https://github.com/openhwgroup/cva6/settings/access
